### ISSUE TITLE
Docker installation and PMS versions

### ISSUE THREAD

**Issue by MilesTEG1** [007revad/Plex_Server_Sync#1]
Hello,
I'm very interested by your script here.
But as I understand the way the config is done, you don't support a PMS in a docker container, right?
Is it possible to add this support?

Another question: is it possible to sync 2 PMS with différents versions?
I may use one for tests, so I will have some new versions (like beta one) on it.
And I want to sync the primary with the test server.
Do you think it is possible?

Thanks in advance.
Miles

**Comment by 007revad** [comment]
It would be possible to add support for PMS in a docker container.

Both PMS versions need to be the same version.

**Comment by MilesTEG1** [comment]
Oh thanks 😄 
I can't wait to see those modifications 😉 

And Ok for the same version.

As I want to make a backup of my PMS installation files, and do some tests sometimes, I'll make sure when the backup is done, both server are on the same version.

**Comment by 007revad** [comment]
I just spent the last 3 hours updating the script to support Plex in docker... then I realised I've updated Synology_Plex_Backup instead of Plex_Server_Sync
https://github.com/007revad/Synology_Plex_Backup

After updating that script to support docker it should be easier to update the Plex_Server_Sync script now.

Plex_Server_Sync already uses SSH.

**Comment by MilesTEG1** [comment]
Oh! This work isn't done for nothing :) Hopefully, you can reuse it on the Plex Sync :d 
Thanks for your work 😃

**Comment by 007revad** [comment]
@MilesTEG1 

Here's a boxing day present for you. I finally had to time to do this. It only took 6 months from your initial request 😞 

**Note:** I have NOT tested it. So either backup Plex first or try it on test data.

https://github.com/007revad/Plex_Server_Sync/releases/tag/v2.0.3

**Comment by 007revad** [comment]
Released https://github.com/007revad/Plex_Server_Sync/releases/tag/v2.0.5 with docker support
